// File generated by FlutterFire CLI.
// This is a placeholder file. You need to run 'flutterfire configure' to generate the actual configuration.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqdlxyrnYGdQNu2FYJn8MXQGGUZDGndqk',
    appId: '1:276199755113:android:4e857305eac385d32781f8',
    messagingSenderId: '276199755113',
    projectId: 'alrasikhoon-57151',
    storageBucket: 'alrasikhoon-57151.firebasestorage.app',
  );

  // TODO: Replace with your actual Firebase configuration

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCz5dI5RxyqbDeXTXtYmZwozXVe-KOOpLM',
    appId: '1:276199755113:ios:7d12088a1d5663e22781f8',
    messagingSenderId: '276199755113',
    projectId: 'alrasikhoon-57151',
    storageBucket: 'alrasikhoon-57151.firebasestorage.app',
    androidClientId: '276199755113-p9nacald4nbqh82ltaee4bqpabq9p1iq.apps.googleusercontent.com',
    iosClientId: '276199755113-00b5apnouhai2s3pskskdrg1a6qj9cva.apps.googleusercontent.com',
    iosBundleId: 'com.alrasikhoon.alRasikhoon',
  );

  // Run 'flutterfire configure' to generate this file

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBxdvbmx1m7hESzE1MdqEatgJ1PZAZYlo',
    appId: '1:276199755113:web:101e883fe6ba7d672781f8',
    messagingSenderId: '276199755113',
    projectId: 'alrasikhoon-57151',
    authDomain: 'alrasikhoon-57151.firebaseapp.com',
    storageBucket: 'alrasikhoon-57151.firebasestorage.app',
    measurementId: 'G-MYHX5YHVYV',
  );

}