"""Extract shaped glyph outlines of الراسخون from Amiri-Bold.

Outputs:
  wordmark.svg           — visual check (word + baseline)
  rasikhoon_wordmark_path.dart — generated Flutter Path builder
  anchors.txt            — descender extreme points (for root-tip dots)

Coordinates in the Dart output: x grows right, y grows DOWN, baseline at
y=0 (so descenders have y>0), left edge of the word at x=0.
"""

import uharfbuzz as hb
from fontTools.ttLib import TTFont
from fontTools.pens.basePen import BasePen

FONT = "./fonts/UthmanicHafsBold.ttf"  # KFGQPC HAFS Uthmanic Script Bold
TEXT = "الراسخون"
OUT = "."


class SegmentPen(BasePen):
    """Records segments in (already offset) font units."""

    def __init__(self, glyphset, dx, dy):
        super().__init__(glyphset)
        self.dx, self.dy = dx, dy
        self.segments = []  # (op, points)

    def _p(self, pt):
        return (pt[0] + self.dx, pt[1] + self.dy)

    def _moveTo(self, pt):
        self.segments.append(("M", [self._p(pt)]))

    def _lineTo(self, pt):
        self.segments.append(("L", [self._p(pt)]))

    def _curveToOne(self, p1, p2, p3):
        self.segments.append(("C", [self._p(p1), self._p(p2), self._p(p3)]))

    def _qCurveToOne(self, p1, p2):
        self.segments.append(("Q", [self._p(p1), self._p(p2)]))

    def _closePath(self):
        self.segments.append(("Z", []))


def main():
    blob = hb.Blob.from_file_path(FONT)
    face = hb.Face(blob)
    font = hb.Font(face)

    buf = hb.Buffer()
    buf.add_str(TEXT)
    buf.guess_segment_properties()
    hb.shape(font, buf, {})

    ttfont = TTFont(FONT)
    glyph_order = ttfont.getGlyphOrder()
    glyphset = ttfont.getGlyphSet()

    all_segments = []
    x = 0.0
    for info, pos in zip(buf.glyph_infos, buf.glyph_positions):
        name = glyph_order[info.codepoint]
        pen = SegmentPen(glyphset, x + pos.x_offset, pos.y_offset)
        glyphset[name].draw(pen)
        all_segments.append((name, pen.segments))
        x += pos.x_advance
    total_advance = x

    # Flip y (font y-up -> canvas y-down), baseline stays y=0.
    def cv(pt):
        return (round(pt[0], 1), round(-pt[1], 1))

    # Bounds
    xs, ys = [], []
    for _, segs in all_segments:
        for _, pts in segs:
            for p in pts:
                q = cv(p)
                xs.append(q[0])
                ys.append(q[1])
    min_x, max_x = min(xs), max(xs)
    min_y, max_y = min(ys), max(ys)  # min_y negative (ascent side)

    # SVG for visual verification
    svg_parts = []
    for _, segs in all_segments:
        d = []
        for op, pts in segs:
            pts = [cv(p) for p in pts]
            if op == "M":
                d.append(f"M{pts[0][0]},{pts[0][1]}")
            elif op == "L":
                d.append(f"L{pts[0][0]},{pts[0][1]}")
            elif op == "Q":
                d.append(f"Q{pts[0][0]},{pts[0][1]} {pts[1][0]},{pts[1][1]}")
            elif op == "C":
                d.append(
                    f"C{pts[0][0]},{pts[0][1]} {pts[1][0]},{pts[1][1]} "
                    f"{pts[2][0]},{pts[2][1]}"
                )
            else:
                d.append("Z")
        svg_parts.append("".join(d))
    pad = 60
    svg = (
        f'<svg xmlns="http://www.w3.org/2000/svg" '
        f'viewBox="{min_x - pad} {min_y - pad} '
        f"{max_x - min_x + 2 * pad} {max_y - min_y + 2 * pad}\" "
        f'style="background:#14501B">\n'
        f'<line x1="{min_x - pad}" y1="0" x2="{max_x + pad}" y2="0" '
        f'stroke="#C9A227" stroke-width="14"/>\n'
        + "".join(
            f'<path d="{d}" fill="#F6F0DF" fill-rule="nonzero"/>\n'
            for d in svg_parts
        )
        + "</svg>\n"
    )
    with open(f"{OUT}/wordmark.svg", "w") as f:
        f.write(svg)

    # Descender anchors: lowest point per glyph that dips below baseline.
    with open(f"{OUT}/anchors.txt", "w") as f:
        for name, segs in all_segments:
            pts = [cv(p) for _, ps in segs for p in ps]
            if not pts:
                continue
            deepest = max(pts, key=lambda q: q[1])
            if deepest[1] > 40:  # meaningfully below baseline
                f.write(f"{name}: deepest {deepest}\n")

    # Dart path builder (shifted so left edge = 0)
    lines = [
        "// GENERATED by scratchpad/extract_wordmark.py — do not edit by",
        "// hand. Shaped glyph outlines of الراسخون from the bundled",
        "// Amiri-Bold (google_fonts/ArefRuqaa-Bold.ttf), HarfBuzz-shaped,",
        "// y-down, baseline at y = 0, left edge at x = 0.",
        "import 'dart:ui';",
        "",
        f"const double kWordmarkAdvance = {round(max_x - min_x, 1)};",
        f"const double kWordmarkAscent = {round(-min_y, 1)};",
        f"const double kWordmarkDescent = {round(max_y, 1)};",
        "",
        "Path buildRasikhoonWordPath() {",
        "  final p = Path()..fillType = PathFillType.nonZero;",
    ]
    for _, segs in all_segments:
        for op, pts in segs:
            pts = [cv(p) for p in pts]
            pts = [(round(q[0] - min_x, 1), q[1]) for q in pts]
            if op == "M":
                lines.append(f"  p.moveTo({pts[0][0]}, {pts[0][1]});")
            elif op == "L":
                lines.append(f"  p.lineTo({pts[0][0]}, {pts[0][1]});")
            elif op == "Q":
                lines.append(
                    f"  p.quadraticBezierTo({pts[0][0]}, {pts[0][1]}, "
                    f"{pts[1][0]}, {pts[1][1]});"
                )
            elif op == "C":
                lines.append(
                    f"  p.cubicTo({pts[0][0]}, {pts[0][1]}, "
                    f"{pts[1][0]}, {pts[1][1]}, {pts[2][0]}, {pts[2][1]});"
                )
            else:
                lines.append("  p.close();")
    lines += ["  return p;", "}", ""]
    with open(f"{OUT}/rasikhoon_wordmark_path.dart", "w") as f:
        f.write("\n".join(lines))

    print(f"advance={total_advance} bounds=({min_x},{min_y})..({max_x},{max_y})")
    print(f"glyphs={[n for n, _ in all_segments]}")


main()
